---
# Install Sublime Text on Debian

- name: Add public key
  ansible.builtin.apt_key:
    url: "{{ sublime_apt_key }}"
    state: present
  become: true

- name: Add repository
  ansible.builtin.apt_repository:
    repo: "{{ sublime_apt_repo }}"
    state: present
    update_cache: yes
  become: true

- name: Install package
  ansible.builtin.apt:
    pkg: "sublime-text={{ sublime_version }}*"
    state: present
  become: true
