---
- hosts: all
  remote_user: root
  become: true
  gather_facts: true
  vars:
    sublime_version: 4
  tasks:
    - name: Check sublime version
      ansible.builtin.command: |
        ls ~/.config
      register: result
      retries: 30

    - name: Check result
      ansible.builtin.debug: var=result.stdout
      when: "'sublime-text-' in result.stdout"
